apiVersion: 3scale.net/v1alpha1
kind: API
metadata:
  name: api-management-as-code-demo
spec:
  3scaleConfig:
    IntegrationMethod: apicast
    credentials:
      secret:
        name: demo-credentials-secret
  plans:
  - name: basic
    limits:
    - max: 100
      metric: hits
      period: month
    - max: 10
      metric: hits
      period: minute
    - max: 0
      metric: create_pet
      period: eternity
    - max: 5
      metric: list_pets
      period: minute
  - name: premium
    limits:
    - max: 1000
      metric: hits
      period: month
    - max: 100
      metric: hits
      period: minute
    - max: 10
      metric: create_pet
      period: month
    - max: 10
      metric: list_pets
      period: minute
  upstream: https://echo-api.3scale.net:443
  OpenAPIDefinition: my-api.yaml
